### ISSUE TITLE
Not able to load MNIST Dataset

### ISSUE THREAD

**Issue by ishaikh1** [gluon-api/gluon-api#7]
I am trying to run the example model on the readme, but I am getting an error when it hits the line that loads in the MNIST dataset. I tried loading in the dataset without any parameters from the python shell as well, but still no progress.

```
>>> x = mx.gluon.data.vision.MNIST()
Downloading /Users/IbrahimShaikh/.mxnet/datasets/train-images-idx3-ubyte.gz from http://data.mxnet.io/data/mnist/train-images-idx3-ubyte.gz...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/mxnet/gluon/data/vision.py", line 75, in __init__
    super(MNIST, self).__init__(root, train, transform)
  File "/usr/local/lib/python2.7/site-packages/mxnet/gluon/data/vision.py", line 43, in __init__
    self._get_data()
  File "/usr/local/lib/python2.7/site-packages/mxnet/gluon/data/vision.py", line 83, in _get_data
    sha1_hash='6c95f4b05d2bf285e1bfb0e7960c31bd3b3f8a7d')
  File "/usr/local/lib/python2.7/site-packages/mxnet/gluon/utils.py", line 200, in download
    r = requests.get(url, stream=True)
AttributeError: type object 'requests_failed_to_import' has no attribute 'get'
```

**Comment by srochel** [comment]
1. please use master version of MXNet: pip install mxnet --pre --user (the latest released version does not include the latest version of the spec).
2. please file MXNet related issues at https://github.com/apache/incubator-mxnet/issues or raise questions at https://discuss.mxnet.io/
